#!/bin/bash -e

#Install directory
DIR=$(dirname $(readlink -fn $0))
cd "$DIR"

USER='mike';
HOME="$(cat /etc/passwd | grep $USER | cut -d : -f 6)";

source ./pprint
export LOGFILE='/var/log/backup.log'
if [ -e $LOGFILE ] ; then rm $LOGFILE ; fi
touch $LOGFILE

SUB="Backup Script *FAILED*"

if [[ "$UID" != "0" ]] ; then
    die_mail "$SUB" "You must be root in order to use this script."
elif [ -z "$HOME" ] ; then
    die_mail "$SUB" "Could not discover the user's home directory"
elif [ ! -d "$HOME" ] ; then
    die_mail "$SUB" "User's home directory, \"$HOME\" is not a directory"
elif ! mount | grep -q /backup ; then
    if mount /backup ; then
        info_log "Mounted the /backup file system"
    else
        die_mail "$SUB" "The /backup file system could not be mounted"
    fi
fi

cat > /tmp/exclude-list <<EOF
**/.gvfs
**/.gtk-bookmarks/.gvfs
**/.mount
**/*Cache
**/*cache
**/Trash
**/Downloads
**/Dropbox
**/test
EOF

info_log Starting backup
if ! rdiff-backup -v 6 --print-statistics --exclude-globbing-filelist /tmp/exclude-list --include $HOME --exclude '**' / /backup/ > /tmp/dump ; then
    error_log "Backup failed, rdiff-backup's output:"
    cat /tmp/dump >> "$LOGFILE"
    die_mail "$SUB" "Backup script failed on $(date)"
else
    info_log "Backup Script Succeeded"
    mail_log "Backup Script Succeeded" "$(date) Backup succeeded"
fi
