#!/bin/bash

if [ -z "$1" ] ; then
  echo "usage: $0 file-to-change"
  exit 1;
fi

sed -i 's|<div class="slide.*">|<section>|
        s|</div>|</section>|
        s|<pre class="brush: \(.*\)">|<pre><code class="\1">|
        s|</pre>|</code></pre>|
        s|print \(.*\)$|print( \1 )|
        s|h1|h2|g
        s|    |  |' "$1"
